# logging
log_dest syslog
log_type error
log_type warning
log_type notice
log_type information
log_type subscribe
log_type unsubscribe
log_timestamp_format %Y-%m-%dT%H:%M:%S

connection_messages true
